NFC: Fix missing symbol
vendor/nxp/opensource/commonsys/packages/apps/Nfc/src/com/android/nfc/handover/BluetoothPeripheralHandover.java:493: error: cannot find symbol
                int reason = intent.getIntExtra(BluetoothDevice.EXTRA_REASON,
                                                               ^
  symbol:   variable EXTRA_REASON
  location: class BluetoothDevice
1 error

This was renamed to EXTRA_UNBOUND_REASON as per this commit: https://github.com/PixelExperience-Staging/packages_modules_Bluetooth/commit/e0328dfcda4ca933f0c8d8fad16ddebd29d6387b